url.discord: "https://discord.com/invite/3a4kdeuDzE"
url.youtube: "https://www.youtube.com/@thefaser"
url.github: "https://github.com/Flectone"
url.author: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

#shaders
shader.BSL: "BSL"
shader.Sildur: "Sildur Enhanced Default"
shader.MakeUp: "MakeUp"
shader.Complementary: "Complementary v4"
shader.ComplementaryReimagined: "Complementary Reimagined"

#farms
farm.debris: "Ancient debris farm"
farm.witherrose: "Wither rose farm"
farm.trident: "Drowned farm"
farm.cobblestone: "Cobblestone farm"
farm.besttree: "Tree farm"
farm.bee: "Bee farm"
farm.newslime: "Slime farm"
farm.lygyxa: "Froglight farm"
farm.turtle: "Turtle farm"
farm.iron: "Iron farm"
farm.gold: "Gold farm"
farm.portalporox: "Gunpowder farm"
farm.afkfish: "AFK-Fishing"
farm.newporox: "Gunpowder Farm"
farm.obsidian: "Obsidian Farm"
farm.oldporox: "old Gunpowder Farm"
farm.oneblock: "Farm one block"
farm.raid: "Raid Farm"
farm.slime: "Slime Farm"
farm.witcher: "Witch Farm"
farm.wither: "Wither Skeleton Farm"
farm.wood: "Wood Farm"
farm.guard: "Guard farm"
farm.squid: "Squid farm"
farm.ender: "Enderman farm"
farm.bestsheep: "Sheep farm"

farm.debris.version: "1.16+"
farm.witherrose.version: "1.16+"
farm.bee.version: "1.15+"
farm.trident.version: "1.18+"
farm.cobblestone.version: "1.18+"
farm.besttree.version: "1.19+"
farm.newslime.version: "1.19+"
farm.lygyxa.version: "1.19+"
farm.turtle.version: "1.13-1.19+"
farm.iron.version: "1.14-1.19+"
farm.gold.version: "1.15-1.19+"
farm.portalporox.version: "1.19+"
farm.afkfish.version: "1.19+"
farm.newporox.version: "1.14-1.19+"
farm.obsidian.version: "1.16-1.19+"
farm.oldporox.version: "1.14-1.19+"
farm.oneblock.version: "1.14-1.19+"
farm.raid.version: "1.17-1.19+"
farm.slime.version: "1.17-1.19+"
farm.witcher.version: "1.17-1.19+"
farm.wither.version: "1.16-1.19+"
farm.wood.version: "1.18-1.19+"
farm.guard.version: "1.16-1.19+"
farm.squid.version: "1.14-1.19+"
farm.ender.version: "1.16-1.19+"
farm.bestsheep.version: "1.16-1.19+"

#resourcepacks
resourcepack.bluedebris: "Blue ancient debris"
resourcepack.bossbars: "Boss Bars Plus"
resourcepack.discs: "Alternate Discs"
resourcepack.doors: "Flush Doors"
resourcepack.elytra: "Phantom Elytra"
resourcepack.icons: "Better Icons"
resourcepack.ores: "Visible Ores"
resourcepack.potion: "Better Potion"
resourcepack.tools: "Stylized Tools"
resourcepack.torch: "Semi-Iron Torches"
resourcepack.village: "Villagers, Pillagers, Improvements"
resourcepack.bicons: "Icons"
resourcepack.bigbraingui: "Big Brain GUI"
resourcepack.defaultdarkmode: "Default Dark Mode"
resourcepack.ingamebrewingguide: "In-Game Brewing Guide"
resourcepack.numberedhotbar: "Numbered Hotbar"
resourcepack.redstonetweaks: "Redstone Tweaks"
resourcepack.torchesreimagined: "Torches Reimagined"
resourcepack.voidomonenchanted: "Voidomon's Enchanted Books"
resourcepack.Gosha: "Gosha's RPG First Person Pack"
resourcepack.maid-allay: "Maid allay"
resourcepack.mineanvil: "MineAnvil CIT"

#datapacks
datapack.villagetrades: "More Villager Trades"
datapack.cauldron: "Cauldron Upgrade"
datapack.soulorb: "Soul Orbs"
datapack.shears: "More Enchantments For Shears"
datapack.loot: "Better Food and Loot"
datapack.enchant: "Enchant Repair Power"
datapack.craft: "More Crafting Recipes"
datapack.chainarmor: "Chainmail Armor recipe"
datapack.bettervanilla: "Vanilla Expansion"
datapack.alchemy: "Tetrajak's Alchemy"
datapack.Ocean: "[World Generator] Ocean Only World / Water World"
datapack.mangrove: "Vanilla Style Mangrove Villages"

datapack.villagetrades.version: "1.16+"
datapack.cauldron.version: "1.17+"
datapack.soulorb.version: "1.16+"
datapack.shears.version: "1.16+"
datapack.loot.version: "1.17+"
datapack.enchant.version: "1.16+"
datapack.craft.version: "1.16+"
datapack.chainarmor.version: "1.16+"
datapack.bettervanilla.version: "1.17+"
datapack.alchemy.version: "1.16+"
datapack.Ocean.version: "1.19+"
datapack.mangrove.version: "1.19+"

#plugins
plugin.voicechat: "Simple Voice Chat"
plugin.SkinsRestorer: "Skins Restorer"
plugin.plasmovoice: "PlasmoVoice"
plugin.PlaceholderAPI: "Placeholder API"
plugin.LuckPerms: "LuckPerms"
plugin.GSit: "Gsit"
plugin.Geyser: "Geyser"
plugin.FlectoneChat: "FlectoneChat"
plugin.EssentialsX: "EssentialsX"
plugin.CoreProtectTNT: "CoreProtect TNT"
plugin.CoreProtect: "CoreProtect"
plugin.Chunky: "Chunky"
plugin.BlueMap: "BlueMap"
plugin.FartherViewDistance: "FartherViewDistance"

#mods
mod.blur: "Blur"
mod.mixintrace: "MixinTrace"
mod.cullclouds: "Cull Clouds"
mod.Debugify: "Debugify"
mod.Fastload: "FastLoad"
mod.ImmediatelyFast: "ImmediatelyFast"
mod.noxesium: "Noxesium"
mod.exordium: "Exordium"
mod.lunade-fastanim: "FastAnim"
mod.3dskinlayers: "3D Skin Layers"
mod.advancementinfo: "Advancement Info"
mod.appleskin: "Apple Skin"
mod.BetterF3: "Better F3"
mod.bettermounthud: "Better Mount Hud"
mod.borderless-mining: "Borderless Mining"
mod.camerautils: "Camera Utils"
mod.cem: "Custom Entity Models"
mod.chat_heads: "Chat Heads"
mod.chime: "Chime"
mod.CITResewn: "CIT Resewn"
mod.clickthrough: "Click Through"
mod.colormatic: "Color Matic"
mod.Controlling: "Controlling"
mod.DCCH: "Don't Clear Chat History"
mod.DisableCustomWorldsAdvice: "Disable Custom Worlds Advice"
mod.DripSounds: "Drip Sounds"
mod.effective: "Effective"
mod.emotecraft: "EmoteCraft"
mod.EnchantmentDescriptions: "Enchantment Description"
mod.enhanced_attack_indicator: "Enhanced Attack Indicator"
mod.entity_texture_features: "Entity Texture Features"
mod.extrasounds: "Extra Sounds"
mod.fabrishot: "Fabri Shot"
mod.fallingleaves: "Falling Leaves"
mod.firstperson: "First Person"
mod.interactic: "Interactic"
mod.invhud: "Inventory HUD"
mod.item-model-fix: "Item Model Fix"
mod.lambdabettergrass: "Lambda Better Grass"
mod.lambdynamiclights: "Lamb Dynamic Lights"
mod.LegendaryTooltips: "Legendary Tooltips"
mod.MiniEffects: "Mini Effects"
mod.morechathistory: "More Chat History"
mod.mousewheelie: "Mouse Wheelie"
mod.notenoughanimations: "Not Enough Animations"
mod.plasmovoice: "Plasmo Voice"
mod.pling: "Pling"
mod.PresenceFootsteps: "Presence Footsteps"
mod.raised: "Raised"
mod.replaymod: "Replay Mod"
mod.seamless-loading-screen: "Seamless Loading Screen"
mod.sheepconsistency: "Sheep Consistency"
mod.soundphysics: "Sound Physics"
mod.TipTheScales: "Tip The Scales"
mod.tooltipfix: "Tool Tip Fix"
mod.visuality: "Visuality"
mod.WI-Zoom: "WI Zoom"
mod.litematica: "Litematica"
mod.malilib: "Malilib"
mod.RoughlyEnoughItems: "Roughly Enough Items"
mod.accurate-block-placement: "Accurate Block Placement"
mod.AmbientEnvironment: "Ambient Environment"
mod.anakus_status_bars: "Anakus Status Bars"
mod.BBOutlineReloaded: "Bounding Box Outline Reloaded"
mod.ColouredTooltips: "Coloured Tooltips"
mod.customfov: "Custom Fov"
mod.DistantHorizons: "Distant Horizons"
mod.minihud: "Mini HUD"
mod.MouseTweaks: "Mouse Tweaks"
mod.Recipe-Unlocker: "Recipe Unlocker"
mod.worldedit: "World Edit"
mod.Xaeros_Minimap: "Xaeros Mini Map"
mod.BetterThirdPerson: "Better Third Person"
mod.Entity_Collision_FPS_Fix: "Entity Collision Fix"
mod.TieFix: "Tie Fix"
mod.betterbeds: "Better Beds"
mod.betterbiomeblend: "Better Biome Blend"
mod.betterfpsdist: "Better Fps Distant"
mod.bobby: "Bobby"
mod.c2me: "C2ME"
mod.dynamic-fps: "Dynamic Fps"
mod.entityculling: "Entity culling"
mod.fabric-api: "Fabric api"
mod.ferritecore: "Ferritcore"
mod.forgetmechunk: "Forget Me Chunk"
mod.iris: "Iris"
mod.language-reload: "Language Reload"
mod.krypton: "Krypton"
mod.lazydfu: "Lazydfu"
mod.lithium: "Lithium"
mod.modmenu: "Mod Menu"
mod.moreculling: "More Culling"
mod.nofade: "No Fade"
mod.notenoughcrashes: "Not Enough Crashes"
mod.reeses_sodium_options: "Reeses Sodium Options"
mod.smoke-suppression: "Smoke Suppression"
mod.smoothboot: "Smooth Boot"
mod.sodium-extra: "Sodium Extra"
mod.sodium: "Sodium"
mod.starlight: "Starlight"
mod.CullLessLeaves: "Cull Less Leaves"
mod.dashloader: "Dash Loader"
mod.fast-chest: "Fast Chest"
mod.memoryleakfix: "Memory Leak Fix"
mod.cullleaves: "Cull Leaves"
mod.VulkanMod: "Vulkan"
mod.Ksyxis: "Ksyxis"
mod.hydrogen: "Hydrogen"
mod.OptiFine: "OptiFine"
mod.optifabric: "OptiFabric"
mod.saturn: "Saturn"
mod.ItShallNotTick: "It Shall Not Tick"
mod.stendhal: "Stendhal"
mod.slotlock: "Slot Lock"
mod.shulkerboxtooltip: "Shulkerbox Tooltip"
mod.bedrockify: "BedrockIfy"
mod.spyglass-improvements: "Spyglass Improvements"
mod.held-item-info: "Held Item Info"
mod.eating-animation: "Eating Animation"
mod.replanter: "Replanter"
mod.playlist: "Playlist"
mod.itemscroller: "Item Scroller"
mod.skin-swapper: "Skin Swapper"
mod.viafabric: "ViaFabric"
mod.durabilityviewer: "Durability Viewer"
mod.deathlog: "DeathLog"
mod.logical_zoom: "Logical Zoom"
mod.pinglist: "PingList"
mod.isometric-renders: "Isometric Renders"
mod.feytweaks: "FeyTweaks"
mod.Methane: "Methane"
mod.bedrodium: "Bedrodium"
mod.entity-view-distance: "Entity View Distance"
mod.seaborgium: "Seaborgium"